name: MCTT
version: '0.5'
main: lgs.mctt.MCTT
api-version: '1.21'
load: STARTUP
authors: [ KingWesley ]
description: A plugin designed to turn Minecraft into a TTRPG Tabletop.
website:

commands:
  trace:
    description: Find the distance to the block or entity in line of sight.
    usage: /trace
    aliases: [t]
    permission: MCTT.trace
    default: notop
  combat:
    description: Freeze all entities within range
    usage: /combat [range]
    aliases: [freeze, players, fr, pause]
    permission: MCTT.combat
    default: op
  char:
    description: Manage your DnD characters
    usage: /char <create|delete|edit|view> [args]
    aliases: [char, character]
    permission: MCTT.char
    default: notop
  heal:
    description: Heal a player
    usage: /heal [player]
    aliases: [fullheal]
    permission: MCTT.heal
    default: op
  r:
    description: Roll dice using standard notation
    usage: /r <dice number> <dice sides> [modifier], or /r <skill>
    aliases: [roll, dice]
    permission: MCTT.roll
    default: notop

permissions:
    MCTT.trace:
      description: Allows use of the /trace command
      default: true
    MCTT.combat:
      description: Allows use of the /combat command
      default: false
    MCTT.char:
      description: Allows use of the /char command
      default: true
    MCTT.heal:
      description: Allows use of the /heal command
      default: false
    MCTT.r:
      description: Allows use of the /r command
      default: true