name: MCTT
version: '0.4.1'
main: lgs.mctt.MCTT
api-version: '1.21'
load: STARTUP
authors: [ KingWesley ]
description: A plugin designed to turn Minecraft into a TTRPG Tabletop.
website: lootgoblinstudio.com

commands:
  trace:
    description: Find the distance to the block or entity in line of sight.
    usage: /trace
    aliases: [t]
    permission: MCTT.trace
    default: notop
  startcombat:
    description: Freeze all entities within range
    usage: /startcombat [range]
    aliases: [freeze, players, fr, pause]
    permission: MCTT.startcombat
    default: op
  character:
    description: Manage your DnD characters
    usage: /character <create|delete|edit|view> [args]
    aliases: [char, c]
    permission: MCTT.character
    default: notop
  heal:
    description: Heal a player
    usage: /restore [player]
    aliases: [fullheal]
    permission: MCTT.heal
    default: op

permissions:
    MCTT.trace:
      description: Allows use of the /trace command
      default: notop
    MCTT.startcombat:
      description: Allows use of the /startcombat command
      default: op
    MCTT.character:
      description: Allows use of the /character command
      default: op
    MCTT.heal:
      description: Allows use of the /heal command
      default: op